import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";
import GlobalNav from "@/ui/GlobalNav";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: // content,
// navbar,
// modal,
Readonly<{
  children: React.ReactNode;
  // content: React.ReactNode;
  // navbar: React.ReactNode;
  // modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-4">
        <div>
          <GlobalNav />
        </div>
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
